npmScopes:
  "@react-native-google-signin":
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: "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"

npmRegistryServer: "https://registry.npmjs.org"

npmRegistries:
  "https://npm.pkg.github.com":
    npmAuthToken: "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"
