npmScopes:
  "@react-native-google-signin":
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: "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"

npmRegistryServer: "https://registry.npmjs.org"

npmRegistries:
  "https://npm.pkg.github.com":
    npmAuthToken: "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"
